# Pipeline for running SDL scans
# https://aka.ms/yaml

trigger: none

pr:
- master

pool:
  vmImage: 'windows-2019'

variables:
  codeSignPolicyFile: ''
  codeSignEnabled: false

steps:
  - task: DownloadPackage@1
    inputs:
      packageType: 'nuget'
      feed: '529bf55b-43ce-4ca9-a3fd-3c4ed16e057e/16e32dcf-19b6-4e02-b265-9d7f350b9d17'
      definition: 'Microsoft.ConfigurationManager.ConsoleExtension-release'
      version: '5.2203.1080.1000'
      downloadPath: '$(System.ArtifactsDirectory)'

  - task: PowerShell@2
    displayName: "Download, Expand, and Validate Console Extensions"
    inputs:
      filePath: '$(System.ArtifactsDirectory)\scripts\Extensiondownloader.ps1'
      failOnStderr: true
      workingDirectory: '$(Build.SourcesDirectory)\objects'

  - powershell: 'get-childitem env:'
    displayName: "Print variables"

  - task: EsrpMalwareScanning@1
    displayName: 'Run ESRP Malware Scan'
    condition: and(succeeded(), eq(variables['codeSignEnabled'], 'true'))
    inputs:
      ConnectedServiceName: 'ESRP Malware Scanning service connection'
      FolderPath: '$(ESRPScanFolder)'
      Pattern: '*.*'
      Region: 'PuertoRico'
      SessionTimeout: '60'
      MaxConcurrency: '50'
      MaxRetryAttempts: '5'

  - task: securedevelopmentteam.vss-secure-development-tools.build-task-policheck.PoliCheck@1
    displayName: 'Run PoliCheck'
    inputs:
      targetType: F
      targetArgument: '$(Build.SourcesDirectory)\objects'
    continueOnError: true

  - task: securedevelopmentteam.vss-secure-development-tools.build-task-antimalware.AntiMalware@3
    displayName: 'Run AntiMalware Scan'
    inputs:
      FileDirPath: '$(Build.SourcesDirectory)'
      EnableServices: true
      TreatSignatureUpdateFailureAs: 'Error'
      TreatStaleSignatureAs: 'Error'
    continueOnError: true

  - task: CredScan@3
    inputs:
      toolMajorVersion: 'V2'

  - task: securedevelopmentteam.vss-secure-development-tools.build-task-codesignvalidation.CodeSign@1
    inputs:
      Path: '$(Build.SourcesDirectory)\objects\ConsoleExtension'
      verboseOutput: true
      PolicyType: 'Custom'
      PolicyFile: '$(codeSignPolicyFile)'
      ExcludePassesFromLog: false
      FailIfNoTargetsFound: 'false'

  - task: PublishSecurityAnalysisLogs@3
    inputs:
      ArtifactName: 'CodeAnalysisLogs'
      ArtifactType: 'Container'
      AllTools: true
      ToolLogsNotFoundAction: 'Standard'

  - task: PostAnalysis@2
    inputs:
      AllTools: false
      APIScan: false
      BinSkim: false
      CodesignValidation: true
      CodesignValidationBreakOn: 'WarningAbove'
      CredScan: true
      FortifySCA: false
      FxCop: false
      ModernCop: false
      PoliCheck: true
      PoliCheckBreakOn: 'Severity2Above'
      RoslynAnalyzers: false
      SDLNativeRules: false
      Semmle: false
      TSLint: false
      ToolLogsNotFoundAction: 'Error'
